### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by whitequark**
Please see individual commits for descriptions.

### CODE REVIEW

**Comment by japaric** [comment]
@calebmer friendly ping. Any chance you could review this PR? We have on PR blocked on this one. 🙂

**Comment by calebmer** [comment]
Looks good 👍

**Comment by japaric** [comment]
@calebmer Thank you! Could you publish a new release with these changes?

**Comment by calebmer** [comment]
@japaric I’ll get to that tonight. Would you be interested in future maintenance of this crate?

**Comment by japaric** [comment]
>  I’ll get to that tonight.

Thank you!

> Would you be interested in future maintenance of this crate?

Sure :-).

**Comment by calebmer** [comment]
@japaric if you could send me over the links and emails necessary to add you that would be great 😊

**Comment by japaric** [comment]
Hmm, so I think you'll have to add me as a collaborator to this repository using
this link:

https://github.com/calebmer/inflections/settings/collaboration

And then add me as an owner of the inflections crate on crates.io using this
command:

```
$ cd /path/to/inflections

$ cargo owner --add japaric
```

I think that should do it. (I have never used the `cargo owner` command before
but that's what the [documentation] says.)

[documentation]: http://doc.crates.io/crates-io.html#cargo-owner

**Comment by calebmer** [comment]
@japaric done. Feel free to publish the next release 😊

**Comment by japaric** [comment]
@calebmer Thank you! Will do.

**Pull request merged**
